<?php
/** Project petty cash and its idempotent accounting bridge. */
if (!defined('ABSPATH')) { exit; }
final class Paydar_Petty_Cash {
    const SCHEMA='1';
    const READ='paydar_petty_cash_read';
    const MANAGE='paydar_petty_cash_manage';
    const REQUEST='paydar_petty_cash_request';
    const REVIEW='paydar_petty_cash_review';
    const SENIOR='paydar_petty_cash_senior_approve';
    const PAY='paydar_petty_cash_pay';
    const RECONCILE='paydar_petty_cash_reconcile';
    private static $instance;
    public static function boot(){if(!self::$instance)self::$instance=new self();return self::$instance;}
    public static function table($n){global $wpdb;return $wpdb->prefix.'paydar_pc_'.$n;}
    public static function caps(){return array('read'=>current_user_can(self::READ),'manage'=>current_user_can(self::MANAGE),'request'=>current_user_can(self::REQUEST),'review'=>current_user_can(self::REVIEW),'senior'=>current_user_can(self::SENIOR),'pay'=>current_user_can(self::PAY),'reconcile'=>current_user_can(self::RECONCILE));}
    private function __construct(){add_action('plugins_loaded',array(__CLASS__,'upgrade'));add_action('rest_api_init',array($this,'routes'));}
    public static function upgrade(){if(get_option('paydar_petty_cash_schema')!==self::SCHEMA)self::install();}
    public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();$defs=array(
        'settings'=>"id bigint(20) unsigned NOT NULL,\n approval_threshold decimal(20,0) NOT NULL DEFAULT 0,\n PRIMARY KEY  (id)",
        'funds'=>"id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n project_id varchar(32) NOT NULL,\n name varchar(190) NOT NULL,\n custodian_user_id bigint(20) unsigned NOT NULL,\n cash_account_id bigint(20) unsigned NOT NULL,\n limit_amount decimal(20,0) NOT NULL,\n active tinyint(1) NOT NULL DEFAULT 1,\n version bigint(20) unsigned NOT NULL DEFAULT 1,\n created_by bigint(20) unsigned NOT NULL,\n created_at datetime NOT NULL,\n updated_at datetime NOT NULL,\n PRIMARY KEY  (id),\n KEY project_id (project_id),\n UNIQUE KEY cash_account_id (cash_account_id),\n KEY custodian_user_id (custodian_user_id)",
        'categories'=>"id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n name varchar(190) NOT NULL,\n expense_account_id bigint(20) unsigned NOT NULL,\n active tinyint(1) NOT NULL DEFAULT 1,\n version bigint(20) unsigned NOT NULL DEFAULT 1,\n PRIMARY KEY  (id),\n KEY expense_account_id (expense_account_id)",
        'requests'=>"id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n fund_id bigint(20) unsigned NOT NULL,\n amount decimal(20,0) NOT NULL,\n purpose varchar(1000) NOT NULL,\n status varchar(24) NOT NULL DEFAULT 'submitted',\n requested_by bigint(20) unsigned NOT NULL,\n manager_by bigint(20) unsigned DEFAULT NULL,\n accountant_by bigint(20) unsigned DEFAULT NULL,\n senior_by bigint(20) unsigned DEFAULT NULL,\n source_account_id bigint(20) unsigned DEFAULT NULL,\n transfer_date date DEFAULT NULL,\n transfer_ref varchar(190) NOT NULL DEFAULT '',\n paid_by bigint(20) unsigned DEFAULT NULL,\n entry_id bigint(20) unsigned DEFAULT NULL,\n version bigint(20) unsigned NOT NULL DEFAULT 1,\n created_at datetime NOT NULL,\n updated_at datetime NOT NULL,\n PRIMARY KEY  (id),\n KEY fund_status (fund_id,status)",
        'expenses'=>"id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n fund_id bigint(20) unsigned NOT NULL,\n amount decimal(20,0) NOT NULL,\n expense_date date NOT NULL,\n category_id bigint(20) unsigned NOT NULL,\n payee varchar(190) NOT NULL DEFAULT '',\n invoice_ref varchar(190) NOT NULL DEFAULT '',\n invoice_date date DEFAULT NULL,\n document_ref varchar(190) NOT NULL DEFAULT '',\n description varchar(1500) NOT NULL,\n status varchar(24) NOT NULL DEFAULT 'submitted',\n requested_by bigint(20) unsigned NOT NULL,\n manager_by bigint(20) unsigned DEFAULT NULL,\n accountant_by bigint(20) unsigned DEFAULT NULL,\n senior_by bigint(20) unsigned DEFAULT NULL,\n entry_id bigint(20) unsigned DEFAULT NULL,\n posting_key varchar(64) NOT NULL,\n version bigint(20) unsigned NOT NULL DEFAULT 1,\n created_at datetime NOT NULL,\n updated_at datetime NOT NULL,\n PRIMARY KEY  (id),\n UNIQUE KEY posting_key (posting_key),\n KEY fund_status (fund_id,status),\n KEY expense_date (expense_date)",
        'reconciliations'=>"id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n fund_id bigint(20) unsigned NOT NULL,\n as_of_date date NOT NULL,\n book_balance decimal(20,0) NOT NULL,\n pending_amount decimal(20,0) NOT NULL,\n counted_amount decimal(20,0) NOT NULL,\n variance decimal(20,0) NOT NULL,\n reason varchar(1500) NOT NULL DEFAULT '',\n created_by bigint(20) unsigned NOT NULL,\n created_at datetime NOT NULL,\n PRIMARY KEY  (id),\n KEY fund_date (fund_id,as_of_date)",
        'audit'=>"id bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n actor_id bigint(20) unsigned NOT NULL,\n action varchar(40) NOT NULL,\n object_type varchar(24) NOT NULL,\n object_id bigint(20) unsigned NOT NULL DEFAULT 0,\n detail longtext NOT NULL,\n created_at datetime NOT NULL,\n PRIMARY KEY  (id),\n KEY object_ref (object_type,object_id),\n KEY created_at (created_at)"
    );foreach($defs as $name=>$def){$t=self::table($name);dbDelta("CREATE TABLE $t (\n $def\n) ENGINE=InnoDB $c;");$st=$wpdb->get_row($wpdb->prepare('SHOW TABLE STATUS WHERE Name=%s',$t));if(!$st||strtolower($st->Engine)!=='innodb')return;}if($wpdb->query('INSERT IGNORE INTO '.self::table('settings')." (id,approval_threshold) VALUES (1,0)")===false)return;update_option('paydar_petty_cash_schema',self::SCHEMA,false);}
    private static function err($m,$s=400){return new WP_Error('paydar_petty_cash_error',$m,array('status'=>$s));}
    private static function reject($m,$s=400){throw new RuntimeException($m,$s);}
    private static function must($x){if($x===false)self::reject('ذخیره انجام نشد و تغییرات ثبت نشد.',500);return $x;}
    private function permission($cap){global $wpdb;if(!is_user_logged_in())return self::err('ورود لازم است.',401);if(!current_user_can('paydar_access')||!current_user_can($cap))return self::err('دسترسی مجاز نیست.',403);if(get_option('paydar_petty_cash_schema')!==self::SCHEMA||get_option('paydar_accounting_schema')!==Paydar_Accounting::SCHEMA||PHP_INT_SIZE<8)return self::err('زیرساخت تنخواه و حسابداری آماده نیست.',503);if(!$wpdb->get_var('SELECT unit FROM '.Paydar_Accounting::table('settings').' WHERE id=1'))return self::err('مدیر سیستم باید ابتدا واحد پایه حسابداری را انتخاب کند.',503);return true;}
    public function routes(){$routes=array(
        '/petty/settings'=>array(array('GET','settings',self::READ),array('POST','save_settings',self::MANAGE)),
        '/petty/funds'=>array(array('GET','funds',self::READ),array('POST','save_fund',self::MANAGE)),
        '/petty/funds/(?P<id>[1-9][0-9]*)'=>array(array('GET','fund_detail',self::READ)),
        '/petty/funds/(?P<id>[1-9][0-9]*)'=>array(array('PUT','save_fund',self::MANAGE)),
        '/petty/categories'=>array(array('GET','categories',self::READ),array('POST','save_category',self::MANAGE)),
        '/petty/categories/(?P<id>[1-9][0-9]*)'=>array(array('PUT','save_category',self::MANAGE)),
        '/petty/requests'=>array(array('GET','requests',self::READ),array('POST','create_request',self::REQUEST)),
        '/petty/requests/(?P<id>[1-9][0-9]*)'=>array(array('GET','request_detail',self::READ)),
        '/petty/requests/(?P<id>[1-9][0-9]*)/manager'=>array(array('POST','manager_request',self::REVIEW)),
        '/petty/requests/(?P<id>[1-9][0-9]*)/accountant'=>array(array('POST','accountant_request',self::REVIEW)),
        '/petty/requests/(?P<id>[1-9][0-9]*)/senior'=>array(array('POST','senior_request',self::SENIOR)),
        '/petty/requests/(?P<id>[1-9][0-9]*)/reject'=>array(array('POST','reject_request',self::READ)),
        '/petty/requests/(?P<id>[1-9][0-9]*)/pay'=>array(array('POST','pay_request',self::PAY)),
        '/petty/expenses'=>array(array('GET','expenses',self::READ),array('POST','create_expense',self::REQUEST)),
        '/petty/expenses/(?P<id>[1-9][0-9]*)'=>array(array('GET','expense_detail',self::READ)),
        '/petty/expenses/(?P<id>[1-9][0-9]*)/manager'=>array(array('POST','manager_expense',self::REVIEW)),
        '/petty/expenses/(?P<id>[1-9][0-9]*)/accountant'=>array(array('POST','accountant_expense',self::REVIEW)),
        '/petty/expenses/(?P<id>[1-9][0-9]*)/senior'=>array(array('POST','senior_expense',self::SENIOR)),
        '/petty/expenses/(?P<id>[1-9][0-9]*)/reject'=>array(array('POST','reject_expense',self::READ)),
        '/petty/expenses/(?P<id>[1-9][0-9]*)/post'=>array(array('POST','post_expense',self::PAY)),
        '/petty/reconcile'=>array(array('GET','reconcile_list',self::READ),array('POST','reconcile',self::RECONCILE)),
        '/petty/summary'=>array(array('GET','summary',self::READ)),
        '/petty/audit'=>array(array('GET','audit_list',self::READ))
    );foreach($routes as $path=>$defs){$args=array();foreach($defs as $d){$cap=$d[2];$args[]=array('methods'=>$d[0],'callback'=>array($this,$d[1]),'permission_callback'=>function()use($cap){return $this->permission($cap);});}register_rest_route('paydar/v1',''.$path,$args);}}
    private static function body($r){$b=$r->get_json_params();if(!is_array($b))self::reject('بدنه درخواست نامعتبر است.');return $b;}
    private static function raw($v,$max=500){if(!is_string($v)&&!is_int($v))self::reject('مقدار متنی نامعتبر است.');$v=sanitize_textarea_field((string)$v);if(mb_strlen($v)>$max)self::reject('متن بیش از حد طولانی است.');return trim($v);}
    private static function id($r){$p=$r->get_url_params();return isset($p['id'])?(int)$p['id']:0;}
    private static function uid($v){if((!is_int($v)&&!is_string($v))||!preg_match('/^[1-9][0-9]{0,9}$/D',(string)$v))self::reject('شناسه نامعتبر است.');return (int)$v;}
    private static function amount($v){return Paydar_Accounting::amount($v);}
    private static function date($v){return Paydar_Accounting::valid_date($v);}
    private function txn($fn){global $wpdb;try{if(get_option('paydar_petty_cash_schema')!==self::SCHEMA)self::reject('جدول تنخواه آماده نیست.',503);Paydar_Accounting::must_for_modules($wpdb->query('START TRANSACTION'));$lock=$wpdb->get_row('SELECT * FROM '.Paydar_Accounting::table('settings').' WHERE id=1 FOR UPDATE');if(!$lock)self::reject('قفل دفتر مالی در دسترس نیست.',503);$out=$fn();Paydar_Accounting::must_for_modules($wpdb->query('COMMIT'));return rest_ensure_response($out);}catch(Throwable $e){$wpdb->query('ROLLBACK');$c=in_array($e->getCode(),array(400,403,404,409,500,503),true)?$e->getCode():500;return self::err($c===500?'خطای ثبت؛ تغییرات ذخیره نشد.':$e->getMessage(),$c);}}
    private function audit($type,$id,$action,$detail=array()){global $wpdb;self::must($wpdb->insert(self::table('audit'),array('actor_id'=>get_current_user_id(),'action'=>$action,'object_type'=>$type,'object_id'=>$id,'detail'=>wp_json_encode($detail),'created_at'=>current_time('mysql'))));}
    private function fund($id){global $wpdb;return $wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('funds').' WHERE id=%d',$id));}
    private function allowed_fund($f){global $wpdb;if(!$f)self::reject('تنخواه پیدا نشد.',404);if(current_user_can(Paydar_Accounting::READ)||current_user_can('manage_options'))return;if(!current_user_can('paydar_edit_exec_own'))self::reject('به این تنخواه دسترسی ندارید.',403);$p=$wpdb->get_var($wpdb->prepare('SELECT manager_user_id FROM '.$wpdb->prefix.'paydar_projects WHERE project_id=%s',$f->project_id));if((int)$p!==get_current_user_id())self::reject('به این پروژه دسترسی ندارید.',403);}
    public function settings(){global $wpdb;$s=$wpdb->get_row('SELECT * FROM '.self::table('settings').' WHERE id=1');$users=array();if(current_user_can(self::MANAGE)){foreach(get_users(array('role__in'=>array('paydar_project_manager','paydar_accountant'),'orderby'=>'display_name','fields'=>'all')) as $u){$users[]=array('id'=>(int)$u->ID,'name'=>$u->display_name,'role'=>in_array('paydar_project_manager',(array)$u->roles,true)?'مدیر پروژه':'حسابدار');}}return rest_ensure_response(array('approval_threshold'=>(string)$s->approval_threshold,'custodians'=>$users,'can'=>self::caps()));}
    public function save_settings($r){return $this->txn(function()use($r){global $wpdb;$b=self::body($r);$v=(string)self::amount($b['approval_threshold']??'0');self::must($wpdb->update(self::table('settings'),array('approval_threshold'=>$v),array('id'=>1)));$this->audit('settings',1,'settings_updated',array('threshold'=>$v));return array('approval_threshold'=>$v);});}
    public function funds($r){$list=Paydar_Petty_Cash::list_for_user(current_user_can(self::MANAGE)&&$r->get_param('all')==='1');return rest_ensure_response(array('funds'=>$list,'can'=>self::caps()));}
    public static function list_for_user($all=false){global $wpdb;$sql='SELECT f.*,p.name AS project_name,u.display_name AS custodian_name FROM '.self::table('funds').' f JOIN '.$wpdb->prefix.'paydar_projects p ON p.project_id=f.project_id LEFT JOIN '.$wpdb->users.' u ON u.ID=f.custodian_user_id WHERE 1=1';if(!$all)$sql.=' AND f.active=1';if(!current_user_can(Paydar_Accounting::READ)&&!current_user_can('manage_options')){ $sql.=$wpdb->prepare(' AND p.manager_user_id=%d',get_current_user_id());}return $wpdb->get_results($sql.' ORDER BY p.name,f.name');}
    public function fund_detail($r){try{$f=$this->fund(self::id($r));$this->allowed_fund($f);global $wpdb;$f->project_name=$wpdb->get_var($wpdb->prepare('SELECT name FROM '.$wpdb->prefix.'paydar_projects WHERE project_id=%s',$f->project_id));$f->custodian_name=$wpdb->get_var($wpdb->prepare('SELECT display_name FROM '.$wpdb->users.' WHERE ID=%d',$f->custodian_user_id));$f->book_balance=$this->book_balance($f,current_time('Y-m-d'));$f->pending_amount=$this->pending_spent($f->id,current_time('Y-m-d'));$f->expected_cash=(string)((int)$f->book_balance-(int)$f->pending_amount);return rest_ensure_response(array('fund'=>$f,'requests'=>$wpdb->get_results($wpdb->prepare('SELECT id,amount,purpose,status,transfer_date,entry_id,created_at FROM '.self::table('requests').' WHERE fund_id=%d ORDER BY id DESC LIMIT 10',$f->id)),'expenses'=>$wpdb->get_results($wpdb->prepare('SELECT id,amount,expense_date,description,status,entry_id,created_at FROM '.self::table('expenses').' WHERE fund_id=%d ORDER BY id DESC LIMIT 10',$f->id))));}catch(Throwable $e){return self::err($e->getMessage(),in_array($e->getCode(),array(400,403,404),true)?$e->getCode():400);}}
    public function categories(){global $wpdb;return rest_ensure_response(array('categories'=>$wpdb->get_results('SELECT c.*,a.code,a.name AS account_name FROM '.self::table('categories').' c LEFT JOIN '.Paydar_Accounting::table('accounts').' a ON a.id=c.expense_account_id ORDER BY c.name')));}
    private function validate_account($id,$kind){global $wpdb;$a=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Paydar_Accounting::table('accounts').' WHERE id=%d',$id));if(!$a||(int)$a->active!==1||(int)$a->postable!==1||$a->kind!==$kind)self::reject('حساب باید فعال، قابل ثبت و از گروه مناسب باشد.');return $a;}
    public function save_fund($r){return $this->txn(function()use($r){global $wpdb;$b=self::body($r);$id=self::id($r);$old=$id?$this->fund($id):null;if($id&&!$old)self::reject('تنخواه پیدا نشد.',404);if($old&&(int)$old->version!==(int)($b['version']??0))self::reject('تنخواه تغییر کرده؛ صفحه را تازه کنید.',409);$pid=self::raw($b['project_id']??'',32);$p=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.$wpdb->prefix.'paydar_projects WHERE project_id=%s',$pid));if(!$p)self::reject('پروژه پیدا نشد.');$name=self::raw($b['name']??'',190);$uid=self::uid($b['custodian_user_id']??0);$custodian=get_userdata($uid);if(!$custodian||!array_intersect((array)$custodian->roles,array('paydar_project_manager','paydar_accountant')))self::reject('مسئول تنخواه باید مدیر پروژه یا حسابدار سامانه باشد.');$aid=self::uid($b['cash_account_id']??0);$this->validate_account($aid,'asset');$limit=self::amount($b['limit_amount']??'0');if(!$name||$limit<1)self::reject('نام و سقف مثبت لازم است.');if($wpdb->get_var($wpdb->prepare('SELECT id FROM '.self::table('funds').' WHERE cash_account_id=%d AND id<>%d',$aid,$id)))self::reject('هر حساب تنخواه باید به یک صندوق اختصاص یابد.',409);if($old&&($old->project_id!==$pid||(int)$old->cash_account_id!==$aid)){ $activity=(int)$wpdb->get_var($wpdb->prepare('SELECT (SELECT COUNT(*) FROM '.self::table('requests').' WHERE fund_id=%d)+(SELECT COUNT(*) FROM '.self::table('expenses').' WHERE fund_id=%d)+(SELECT COUNT(*) FROM '.self::table('reconciliations').' WHERE fund_id=%d)',$id,$id,$id)); if($activity)self::reject('پروژه و حساب تنخواه پس از شروع گردش قابل تغییر نیستند.'); }$data=array('project_id'=>$pid,'name'=>$name,'custodian_user_id'=>$uid,'cash_account_id'=>$aid,'limit_amount'=>(string)$limit,'active'=>array_key_exists('active',$b)?(int)!!$b['active']:($old?(int)$old->active:1),'version'=>$old?(int)$old->version+1:1,'updated_at'=>current_time('mysql'));if($old)self::must($wpdb->update(self::table('funds'),$data,array('id'=>$id)));else{$data+=array('created_by'=>get_current_user_id(),'created_at'=>current_time('mysql'));self::must($wpdb->insert(self::table('funds'),$data));$id=(int)$wpdb->insert_id;}$this->audit('fund',$id,$old?'fund_updated':'fund_created',$data);return array('fund'=>$this->fund($id));});}
    public function save_category($r){return $this->txn(function()use($r){global $wpdb;$b=self::body($r);$id=self::id($r);$old=$id?$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('categories').' WHERE id=%d',$id)):null;if($id&&!$old)self::reject('دسته هزینه پیدا نشد.',404);if($old&&(int)$old->version!==(int)($b['version']??0))self::reject('دسته تغییر کرده است.',409);$name=self::raw($b['name']??'',190);$aid=self::uid($b['expense_account_id']??0);$this->validate_account($aid,'expense');if(!$name)self::reject('نام دسته الزامی است.');if($old&&(int)$old->expense_account_id!==$aid&&(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.self::table('expenses').' WHERE category_id=%d',$id)))self::reject('دسته استفاده‌شده قابل تغییر حساب نیست.');$data=array('name'=>$name,'expense_account_id'=>$aid,'active'=>array_key_exists('active',$b)?(int)!!$b['active']:1,'version'=>$old?(int)$old->version+1:1);if($old)self::must($wpdb->update(self::table('categories'),$data,array('id'=>$id)));else{self::must($wpdb->insert(self::table('categories'),$data));$id=(int)$wpdb->insert_id;}$this->audit('category',$id,$old?'category_updated':'category_created',$data);return array('category'=>$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('categories').' WHERE id=%d',$id)));});}
    private function paged($table,$type,$r){global $wpdb;$page=max(1,min(100000,(int)$r->get_param('page')));$where='1=1';if(!current_user_can(Paydar_Accounting::READ)&&!current_user_can('manage_options'))$where.=$wpdb->prepare(' AND fund_id IN (SELECT f.id FROM '.self::table('funds').' f JOIN '.$wpdb->prefix.'paydar_projects p ON p.project_id=f.project_id WHERE p.manager_user_id=%d)',get_current_user_id());$fid=$r->get_param('fund_id');if($fid){$fund=$this->fund(self::uid($fid));$this->allowed_fund($fund);$where.=$wpdb->prepare(' AND fund_id=%d',(int)$fund->id);}$status=$r->get_param('status');if($status){$allowed=$type==='expense'?array('submitted','manager_approved','accountant_approved','senior_approved','posting_error','posted','rejected'):array('submitted','manager_approved','accountant_approved','senior_approved','posting','posting_error','paid','rejected');if(!in_array($status,$allowed,true))self::reject('وضعیت نامعتبر است.');$where.=$wpdb->prepare(' AND status=%s',$status);}$rows=$wpdb->get_results("SELECT * FROM $table WHERE $where ORDER BY id DESC LIMIT 30 OFFSET ".(($page-1)*30));$count=(int)$wpdb->get_var("SELECT COUNT(*) FROM $table WHERE $where");foreach($rows as $row)$this->allowed_fund($this->fund((int)$row->fund_id));return array($rows,$count,$page);}
    public function requests($r){global $wpdb;try{list($a,$n,$p)=$this->paged(self::table('requests'),'request',$r);return rest_ensure_response(array('requests'=>$a,'total'=>$n,'page'=>$p));}catch(Throwable $e){return self::err($e->getMessage(),$e->getCode()?:400);}}
    public function expenses($r){global $wpdb;try{list($a,$n,$p)=$this->paged(self::table('expenses'),'expense',$r);return rest_ensure_response(array('expenses'=>$a,'total'=>$n,'page'=>$p));}catch(Throwable $e){return self::err($e->getMessage(),$e->getCode()?:400);}}
    private function state_row($table,$id){global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE id=%d",$id));}
    private function project_access($fund){$this->allowed_fund($fund);}
    public function create_request($r){return $this->txn(function()use($r){global $wpdb;$b=self::body($r);$f=$this->fund(self::uid($b['fund_id']??0));$this->project_access($f);if(!(int)$f->active)self::reject('تنخواه غیرفعال است.');$amount=self::amount($b['amount']??'');if($amount<1||$amount>(int)$f->limit_amount)self::reject('مبلغ باید مثبت و در سقف تنخواه باشد.');$asof=current_time('Y-m-d');$book=$this->book_balance($f,$asof);$spent=$this->pending_spent($f->id,$asof);$outstanding=(string)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(amount),0) FROM ".self::table('requests')." WHERE fund_id=%d AND status NOT IN ('paid','rejected')",$f->id));$over=$wpdb->get_var($wpdb->prepare('SELECT (CAST(%s AS DECIMAL(20,0))-CAST(%s AS DECIMAL(20,0))+CAST(%s AS DECIMAL(20,0))+CAST(%s AS DECIMAL(20,0)))>CAST(%s AS DECIMAL(20,0))', $book,$spent,$outstanding,(string)$amount,(string)$f->limit_amount));if($over)self::reject('موجودی مورد انتظار به‌همراه شارژهای باز از سقف تنخواه بیشتر می‌شود.',409);$purpose=self::raw($b['purpose']??'',1000);if(!$purpose)self::reject('علت شارژ الزامی است.');self::must($wpdb->insert(self::table('requests'),array('fund_id'=>$f->id,'amount'=>(string)$amount,'purpose'=>$purpose,'status'=>(!current_user_can(Paydar_Accounting::READ)&&!current_user_can('manage_options')?'manager_approved':'submitted'),'requested_by'=>get_current_user_id(),'manager_by'=>(!current_user_can(Paydar_Accounting::READ)&&!current_user_can('manage_options'))?get_current_user_id():null,'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql'))));$id=(int)$wpdb->insert_id;$this->audit('request',$id,'request_submitted',array('site_attested'=>!current_user_can(Paydar_Accounting::READ)&&!current_user_can('manage_options')));return array('request'=>$this->state_row(self::table('requests'),$id));});}
    public function create_expense($r){return $this->txn(function()use($r){global $wpdb;$b=self::body($r);$f=$this->fund(self::uid($b['fund_id']??0));$this->project_access($f);if(!(int)$f->active)self::reject('تنخواه غیرفعال است.');$amount=self::amount($b['amount']??'');if($amount<1)self::reject('مبلغ باید مثبت باشد.');$date=self::date($b['expense_date']??'');if($date>current_time('Y-m-d'))self::reject('تاریخ هزینه در آینده است.');$cat=self::uid($b['category_id']??0);$c=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('categories').' WHERE id=%d AND active=1',$cat));if(!$c)self::reject('دسته فعال هزینه انتخاب کنید.');$desc=self::raw($b['description']??'',1500);if(!$desc)self::reject('شرح هزینه الزامی است.');$idkey='pending-'.wp_generate_password(32,false,false);$data=array('fund_id'=>$f->id,'amount'=>(string)$amount,'expense_date'=>$date,'category_id'=>$cat,'payee'=>self::raw($b['payee']??'',190),'invoice_ref'=>self::raw($b['invoice_ref']??'',190),'invoice_date'=>!empty($b['invoice_date'])?self::date($b['invoice_date']):null,'document_ref'=>self::raw($b['document_ref']??'',190),'description'=>$desc,'status'=>(!current_user_can(Paydar_Accounting::READ)&&!current_user_can('manage_options')?'manager_approved':'submitted'),'requested_by'=>get_current_user_id(),'manager_by'=>(!current_user_can(Paydar_Accounting::READ)&&!current_user_can('manage_options'))?get_current_user_id():null,'posting_key'=>$idkey,'version'=>1,'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql'));self::must($wpdb->insert(self::table('expenses'),$data));$id=(int)$wpdb->insert_id;$postingKey='pc-expense-event-'.$id;self::must($wpdb->update(self::table('expenses'),array('posting_key'=>$postingKey),array('id'=>$id)));$this->audit('expense',$id,'expense_submitted',array('amount'=>(string)$amount,'site_attested'=>!current_user_can(self::READ)));return array('expense'=>$this->state_row(self::table('expenses'),$id));});}
    private function decide($type,$id,$action,$r){return $this->txn(function()use($type,$id,$action,$r){global $wpdb;$table=self::table($type==='expense'?'expenses':'requests');$row=$this->state_row($table,$id);if(!$row)self::reject('درخواست پیدا نشد.',404);$f=$this->fund((int)$row->fund_id);$this->project_access($f);$b=self::body($r);if((int)$row->version!==self::uid($b['version']??0))self::reject('درخواست تغییر کرده است؛ صفحه را تازه کنید.',409);if((int)$row->requested_by===get_current_user_id())self::reject('ثبت‌کننده نمی‌تواند درخواست خودش را تأیید کند.',403);if($action==='accountant' && current_user_can('paydar_edit_exec_own')&&!current_user_can('manage_options'))self::reject('مدیر پروژه نمی‌تواند مرحله مالی را تأیید کند.',403);if($action==='manager'){if(!(int)current_user_can('paydar_edit_exec_own')||current_user_can(Paydar_Accounting::READ))self::reject('فقط مدیر پروژه می‌تواند این مرحله را بررسی کند.',403);if($row->status!=='submitted')self::reject('درخواست در این مرحله نیست.',409);$status='manager_approved';$field='manager_by';}elseif($action==='accountant'){if(!current_user_can(self::REVIEW)||(current_user_can('paydar_edit_exec_own')&&!current_user_can('manage_options')))self::reject('دسترسی حسابدار لازم است.',403);$allowed=$type==='expense'?'manager_approved':'manager_approved';if($row->status!==$allowed)self::reject('درخواست هنوز تأیید مدیر پروژه ندارد.',409);$field='accountant_by';$status='accountant_approved';}elseif($action==='senior'){if(!current_user_can(self::SENIOR)||(current_user_can(self::PAY)&&!current_user_can('manage_options')))self::reject('دسترسی مدیر ارشد لازم است.',403);if($row->status!=='accountant_approved')self::reject('درخواست در انتظار تأیید مدیر ارشد نیست.',409);$settings=$wpdb->get_row('SELECT approval_threshold FROM '.self::table('settings').' WHERE id=1');if(!$settings||(int)$row->amount<(int)$settings->approval_threshold||!(int)$settings->approval_threshold)self::reject('این درخواست به تأیید مدیر ارشد نیاز ندارد.',409);$field='senior_by';$status='senior_approved';}else self::reject('اقدام نامعتبر است.');$this->audit($type,$id,$action,array('from'=>$row->status,'to'=>$status));self::must($wpdb->update($table,array('status'=>$status,$field=>get_current_user_id(),'version'=>(int)$row->version+1,'updated_at'=>current_time('mysql')),array('id'=>$id,'version'=>$row->version)));return array($type=>$this->state_row($table,$id));});}
    public function manager_request($r){return $this->decide('request',self::id($r),'manager',$r);}public function accountant_request($r){return $this->decide('request',self::id($r),'accountant',$r);}public function senior_request($r){return $this->decide('request',self::id($r),'senior',$r);}public function manager_expense($r){return $this->decide('expense',self::id($r),'manager',$r);}public function accountant_expense($r){return $this->decide('expense',self::id($r),'accountant',$r);}public function senior_expense($r){return $this->decide('expense',self::id($r),'senior',$r);}
    private function reject_item($table,$type,$r){return $this->txn(function()use($table,$type,$r){global $wpdb;$id=self::id($r);$row=$this->state_row(self::table($table),$id);if(!$row)self::reject('درخواست پیدا نشد.',404);$this->project_access($this->fund((int)$row->fund_id));$b=self::body($r);$reason=self::raw($b['reason']??'',1000);if(!$reason)self::reject('علت رد الزامی است.');if((int)$row->requested_by===get_current_user_id())self::reject('ثبت‌کننده نمی‌تواند درخواست خودش را رد کند.',403);if(!in_array($row->status,array('submitted','manager_approved','accountant_approved'),true))self::reject('درخواست در این مرحله قابل رد نیست.',409);if($table==='requests'&&!current_user_can(self::PAY)&&!current_user_can(self::SENIOR))self::reject('دسترسی رد درخواست ندارید.',403);if($table==='expenses'&&!current_user_can(self::REVIEW)&&!current_user_can(self::SENIOR))self::reject('دسترسی رد درخواست ندارید.',403);$this->audit($type,$id,'rejected',array('reason'=>$reason));self::must($wpdb->update(self::table($table),array('status'=>'rejected','version'=>(int)$row->version+1,'updated_at'=>current_time('mysql')),array('id'=>$id,'version'=>$row->version)));return array($type=>$this->state_row(self::table($table),$id));});}
    public function reject_request($r){return $this->reject_item('requests','request',$r);}public function reject_expense($r){return $this->reject_item('expenses','expense',$r);}
    private function reserve_post($table,$id,$version,$allowed,$type,$extra=array()){global $wpdb;return $this->txn(function()use($table,$id,$version,$allowed,$type,$extra){global $wpdb;$row=$this->state_row(self::table($table),$id);if(!$row)self::reject('درخواست پیدا نشد.',404);$this->allowed_fund($this->fund((int)$row->fund_id));if((int)$row->version!==(int)$version)self::reject('درخواست تغییر کرده است؛ صفحه را تازه کنید.',409);if(!in_array($row->status,$allowed,true))self::reject('درخواست در مرحله ثبت مالی یا تلاش مجدد نیست.',409);$this->audit($type,$id,'posting_started',array('from'=>$row->status));self::must($wpdb->update(self::table($table),array_merge($extra,array('status'=>'posting','version'=>(int)$row->version+1,'updated_at'=>current_time('mysql'))),array('id'=>$id,'version'=>$row->version)));return array('record'=>$this->state_row(self::table($table),$id));});}
    private function finish_post($table,$id,$entry,$extra=array()) {global $wpdb;$response=$this->txn(function()use($table,$id,$entry,$extra){global $wpdb;$row=$this->state_row(self::table($table),$id);if(!$row||!in_array($row->status,array('posting','posting_error'),true))self::reject('وضعیت ثبت مالی تغییر کرده است.',409);$data=array_merge($extra,array('status'=>$table==='requests'?'paid':'posted','entry_id'=>$entry,'version'=>(int)$row->version+1,'updated_at'=>current_time('mysql')));self::must($wpdb->update(self::table($table),$data,array('id'=>$id,'version'=>$row->version)));$this->audit($table==='requests'?'request':'expense',$id,'posted',array('entry_id'=>$entry));return array(($table==='requests'?'request':'expense')=>$this->state_row(self::table($table),$id),'entry_id'=>$entry);});if(is_wp_error($response))return $response;return $response instanceof WP_REST_Response?$response->data:$response;}
    private function mark_post_error($table,$id,$message){global $wpdb;$this->txn(function()use($table,$id,$message){global $wpdb;$r=$this->state_row(self::table($table),$id);if($r&&$r->status==='posting'){self::must($wpdb->update(self::table($table),array('status'=>'posting_error','version'=>(int)$r->version+1,'updated_at'=>current_time('mysql')),array('id'=>$id,'version'=>$r->version)));$this->audit($table==='requests'?'request':'expense',$id,'posting_error',array('message'=>$message));}return true;});}
    public function pay_request($r){global $wpdb;$id=self::id($r);$b=self::body($r);$row=$this->state_row(self::table('requests'),$id);if(!$row)return self::err('درخواست پیدا نشد.',404);$f=$this->fund((int)$row->fund_id);$this->allowed_fund($f);if((int)$row->requested_by===get_current_user_id())return self::err('ثبت‌کننده درخواست نمی‌تواند پرداخت آن را ثبت کند.',403);try{$date=self::date($b['transfer_date']??'');$aid=self::uid($b['source_account_id']??0);if(in_array($row->status,array('posting','posting_error'),true)&&($row->transfer_date!==$date||(int)$row->source_account_id!==$aid||$row->transfer_ref!==self::raw($b['transfer_ref']??'',190)))self::reject('ثبت انتقال قبلاً آغاز شده؛ مشخصات اولیه را بدون تغییر دوباره بفرستید.',409);$this->validate_account($aid,'asset');$ref=self::raw($b['transfer_ref']??'',190);if($aid===(int)$f->cash_account_id)self::reject('حساب مبدأ و مقصد شارژ باید متفاوت باشند.');if(!$ref)self::reject('شماره رسید یا پیگیری انتقال لازم است.');$cfg=$wpdb->get_row('SELECT approval_threshold FROM '.self::table('settings').' WHERE id=1');if($cfg&&(int)$row->amount>=(int)$cfg->approval_threshold&&(int)$cfg->approval_threshold&&$row->status==='accountant_approved')self::reject('تأیید مدیر ارشد لازم است.',409);}catch(Throwable $e){return self::err($e->getMessage(),$e->getCode()?:400);}$reserved=$this->reserve_post('requests',$id,$b['version']??0,array('accountant_approved','senior_approved','posting_error','posting'),'request',array('source_account_id'=>$aid,'transfer_date'=>$date,'transfer_ref'=>$ref,'paid_by'=>get_current_user_id()));if(is_wp_error($reserved))return $reserved;$row=$reserved instanceof WP_REST_Response?$reserved->data['record']:$reserved['record'];$res=Paydar_Accounting::boot()->post_generated_entry('pc-replenishment-event-'.$id,$date,'شارژ تنخواه '.$f->name.' — '.$row->purpose,'petty_cash_replenishment',(string)$id,array(array('account_id'=>(int)$f->cash_account_id,'project_id'=>$f->project_id,'description'=>'شارژ تنخواه','debit'=>(string)$row->amount,'credit'=>'0'),array('account_id'=>$aid,'project_id'=>'','description'=>'انتقال به تنخواه','debit'=>'0','credit'=>(string)$row->amount)));if(is_wp_error($res)){$this->mark_post_error('requests',$id,$res->get_error_message());return $res;}return $this->finish_post('requests',$id,$res['entry']->id,array('source_account_id'=>$aid,'transfer_date'=>$date,'transfer_ref'=>$ref,'paid_by'=>get_current_user_id()));}
    public function post_expense($r){global $wpdb;$id=self::id($r);$row=$this->state_row(self::table('expenses'),$id);if(!$row)return self::err('هزینه پیدا نشد.',404);$f=$this->fund((int)$row->fund_id);$this->allowed_fund($f);$cfg=$wpdb->get_row('SELECT approval_threshold FROM '.self::table('settings').' WHERE id=1');if($cfg&&(int)$row->amount>=(int)$cfg->approval_threshold&&(int)$cfg->approval_threshold&&$row->status==='accountant_approved')return self::err('تأیید مدیر ارشد لازم است.',409);$body=self::body($r);$reserved=$this->reserve_post('expenses',$id,$body['version']??0,array('accountant_approved','senior_approved','posting_error','posting'),'expense');if(is_wp_error($reserved))return $reserved;$row=$reserved instanceof WP_REST_Response?$reserved->data['record']:$reserved['record'];$cat=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.self::table('categories').' WHERE id=%d',$row->category_id));if(!$cat){$this->mark_post_error('expenses',$id,'دسته هزینه پیدا نشد.');return self::err('دسته هزینه پیدا نشد.',409);}$res=Paydar_Accounting::boot()->post_generated_entry($row->posting_key,$row->expense_date,'هزینه تنخواه '.$f->name.' — '.$row->description,'petty_cash_expense',(string)$id,array(array('account_id'=>(int)$cat->expense_account_id,'project_id'=>$f->project_id,'description'=>$row->description,'debit'=>(string)$row->amount,'credit'=>'0'),array('account_id'=>(int)$f->cash_account_id,'project_id'=>$f->project_id,'description'=>'پرداخت تنخواه','debit'=>'0','credit'=>(string)$row->amount)));if(is_wp_error($res)){$this->mark_post_error('expenses',$id,$res->get_error_message());return $res;}return $this->finish_post('expenses',$id,$res['entry']->id);}
    private function detail($table,$id){global $wpdb;$r=$this->state_row(self::table($table),$id);if(!$r)self::reject('مورد پیدا نشد.',404);$f=$this->fund((int)$r->fund_id);$this->allowed_fund($f);$r->fund_name=$f->name;$r->project_id=$f->project_id;$r->project_name=$wpdb->get_var($wpdb->prepare('SELECT name FROM '.$wpdb->prefix.'paydar_projects WHERE project_id=%s',$f->project_id));if($table==='expenses'){$r->category=$wpdb->get_row($wpdb->prepare('SELECT c.*,a.code,a.name AS account_name FROM '.self::table('categories').' c JOIN '.Paydar_Accounting::table('accounts').' a ON a.id=c.expense_account_id WHERE c.id=%d',$r->category_id));}return $r;}
    public function request_detail($r){try{return rest_ensure_response(array('request'=>$this->detail('requests',self::id($r))));}catch(Throwable $e){return self::err($e->getMessage(),$e->getCode()?:400);}}
    public function expense_detail($r){try{return rest_ensure_response(array('expense'=>$this->detail('expenses',self::id($r))));}catch(Throwable $e){return self::err($e->getMessage(),$e->getCode()?:400);}}
    public function reconcile_list($r){global $wpdb;try{$f=$this->fund(self::uid($r->get_param('fund_id')??0));$this->allowed_fund($f);$rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::table('reconciliations').' WHERE fund_id=%d ORDER BY as_of_date DESC,id DESC LIMIT 30',$f->id));return rest_ensure_response(array('reconciliations'=>$rows));}catch(Throwable $e){return self::err($e->getMessage(),$e->getCode()?:400);}}
    private function pending_spent($fund_id,$date){global $wpdb;$t=self::table('expenses');$sql=$wpdb->prepare("SELECT COALESCE(SUM(x.amount),0) FROM $t x WHERE x.fund_id=%d AND x.expense_date<=%s AND x.status IN ('submitted','manager_approved','accountant_approved','senior_approved','posting','posting_error') AND (x.status<>'posting' OR NOT EXISTS (SELECT 1 FROM ".Paydar_Accounting::table('entries')." e WHERE e.status='posted' AND e.source_type='petty_cash_expense' AND e.source_id=CAST(x.id AS CHAR)))",$fund_id,$date);return (string)$wpdb->get_var($sql);}
    private function book_balance($f,$date){global $wpdb;$sql=$wpdb->prepare("SELECT COALESCE(SUM(l.debit-l.credit),0) FROM ".Paydar_Accounting::table('lines')." l JOIN ".Paydar_Accounting::table('entries')." e ON e.id=l.entry_id WHERE e.status='posted' AND l.account_id=%d AND e.entry_date<=%s",$f->cash_account_id,$date);return (string)$wpdb->get_var($sql);}
    public function reconcile($r){return $this->txn(function()use($r){global $wpdb;$b=self::body($r);$f=$this->fund(self::uid($b['fund_id']??0));$this->allowed_fund($f);$date=self::date($b['as_of_date']??'');$count=self::amount($b['counted_amount']??'');$reason=self::raw($b['reason']??'',1500);$book=$this->book_balance($f,$date);$pending=$this->pending_spent($f->id,$date);$variance=(string)((int)$count-((int)$book-(int)$pending));self::must($wpdb->insert(self::table('reconciliations'),array('fund_id'=>$f->id,'as_of_date'=>$date,'book_balance'=>$book,'pending_amount'=>$pending,'counted_amount'=>(string)$count,'variance'=>$variance,'reason'=>$reason,'created_by'=>get_current_user_id(),'created_at'=>current_time('mysql'))));$id=(int)$wpdb->insert_id;$this->audit('reconciliation',$id,'reconciled',array('variance'=>$variance));return array('reconciliation'=>$this->state_row(self::table('reconciliations'),$id));});}
    public function summary($r){global $wpdb;try{$sql='SELECT f.*,p.name AS project_name FROM '.self::table('funds').' f JOIN '.$wpdb->prefix.'paydar_projects p ON p.project_id=f.project_id WHERE 1=1';if(!$all)$sql.=' AND f.active=1';if(!current_user_can(Paydar_Accounting::READ)&&!current_user_can('manage_options'))$sql.=$wpdb->prepare(' AND p.manager_user_id=%d',get_current_user_id());$funds=$wpdb->get_results($sql.' ORDER BY p.name,f.name');$out=array();$asof=self::date($r->get_param('to')?:current_time('Y-m-d'));foreach($funds as $f){$this->allowed_fund($f);$pending=(string)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(amount),0) FROM ".self::table('expenses')." WHERE fund_id=%d AND expense_date<=%s AND status IN ('submitted','manager_approved','accountant_approved','senior_approved','posting_error')",$f->id,$asof));$book=$this->book_balance($f,$asof);$out[]=array('fund_id'=>$f->id,'fund'=>$f->name,'project_id'=>$f->project_id,'project_name'=>$f->project_name,'custodian_user_id'=>$f->custodian_user_id,'limit_amount'=>(string)$f->limit_amount,'book_balance'=>$book,'pending_amount'=>$pending,'expected_cash'=>(string)((int)$book-(int)$pending),'unit'=>(string)$wpdb->get_var('SELECT unit FROM '.Paydar_Accounting::table('settings').' WHERE id=1'));}return rest_ensure_response(array('funds'=>$out));}catch(Throwable $e){return self::err($e->getMessage(),$e->getCode()?:400);}}
    public function audit_list($r){global $wpdb;$page=max(1,min(100000,(int)$r->get_param('page')));$t=self::table('audit');$where='1=1';if(!current_user_can(Paydar_Accounting::READ)&&!current_user_can('manage_options')){$uid=get_current_user_id();$ids=array();foreach(array('request'=>'requests','expense'=>'expenses','reconciliation'=>'reconciliations') as $kind=>$table)$ids[]=$wpdb->prepare("(object_type=%s AND object_id IN (SELECT z.id FROM ".self::table($table)." z JOIN ".self::table('funds')." f ON f.id=z.fund_id JOIN ".$wpdb->prefix."paydar_projects p ON p.project_id=f.project_id WHERE p.manager_user_id=%d))",$kind,$uid);$where='('.implode(' OR ',$ids).')';}return rest_ensure_response(array('events'=>$wpdb->get_results("SELECT id,actor_id,action,object_type,object_id,created_at FROM $t WHERE $where ORDER BY id DESC LIMIT 50 OFFSET ".(($page-1)*50)),'total'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE $where"),'page'=>$page));}
}
Paydar_Petty_Cash::boot();
