<?php
/**
 * Tables {prefix}akph_*. Created and upgraded only with dbDelta, which adds missing tables, columns and
 * indexes and never drops or rebuilds anything. The stored version (option akph_portal_db_version) is
 * compared on every request (plugins_loaded), so an upgrade by replacing files migrates too.
 */
if (!defined('ABSPATH')) {
    exit;
}

final class Akph_Schema {
    const DB_VERSION = '7';
    const OPTION_VERSION = 'akph_portal_db_version';
    /** Tables that are not InnoDB (transactions and row locks would silently not work). */
    const OPTION_ENGINE_PROBLEMS = 'akph_portal_engine_problems';
    /**
     * Set for an hour after a migration that left tables off InnoDB: the automatic migration on
     * plugins_loaded is not repeated on every request meanwhile (activation and the settings screen retry).
     */
    const TRANSIENT_BACKOFF = 'akph_portal_migrate_backoff';
    const BACKOFF_SECONDS = 3600;

    public static function table($name) {
        global $wpdb;
        return $wpdb->prefix . 'akph_' . $name;
    }

    /** Column definitions. Amounts are integer Rials in BIGINT; dates are Gregorian DATE; times are UTC. */
    public static function definitions() {
        return array(
            'projects' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 code varchar(32) NOT NULL,
 name varchar(190) NOT NULL,
 client_id bigint(20) unsigned NOT NULL DEFAULT 0,
 client_name varchar(190) NOT NULL DEFAULT '',
 consultant_name varchar(190) NOT NULL DEFAULT '',
 manager_user_id bigint(20) unsigned NOT NULL DEFAULT 0,
 site_supervisor varchar(190) NOT NULL DEFAULT '',
 location varchar(190) NOT NULL DEFAULT '',
 contract_ref varchar(64) NOT NULL DEFAULT '',
 description text NULL,
 status varchar(24) NOT NULL DEFAULT 'active',
 physical_progress tinyint(3) unsigned NOT NULL DEFAULT 0,
 start_date date NULL DEFAULT NULL,
 end_date date NULL DEFAULT NULL,
 budget bigint(20) NOT NULL DEFAULT 0,
 contract_amount bigint(20) NOT NULL DEFAULT 0,
 manual_revenue bigint(20) NOT NULL DEFAULT 0,
 manual_cost bigint(20) NOT NULL DEFAULT 0,
 manual_cash bigint(20) NOT NULL DEFAULT 0,
 manual_receivable bigint(20) NOT NULL DEFAULT 0,
 manual_payable bigint(20) NOT NULL DEFAULT 0,
 manual_summary_note varchar(255) NOT NULL DEFAULT '',
 legacy_id varchar(64) NULL DEFAULT NULL,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_by bigint(20) unsigned NOT NULL DEFAULT 0,
 created_at datetime NOT NULL,
 updated_by bigint(20) unsigned NOT NULL DEFAULT 0,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY code (code),
 UNIQUE KEY legacy_id (legacy_id),
 KEY manager_user_id (manager_user_id),
 KEY status (status)",
            'cost_centers' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 code varchar(32) NOT NULL,
 name varchar(190) NOT NULL,
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 type varchar(32) NOT NULL DEFAULT '',
 manager_name varchar(190) NOT NULL DEFAULT '',
 budget bigint(20) NOT NULL DEFAULT 0,
 active tinyint(1) NOT NULL DEFAULT 1,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_by bigint(20) unsigned NOT NULL DEFAULT 0,
 created_at datetime NOT NULL,
 updated_by bigint(20) unsigned NOT NULL DEFAULT 0,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY code (code),
 KEY project_id (project_id)",
            'counterparties' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 kind varchar(16) NOT NULL,
 name varchar(190) NOT NULL,
 national_id varchar(16) NOT NULL DEFAULT '',
 economic_code varchar(20) NOT NULL DEFAULT '',
 phone varchar(32) NOT NULL DEFAULT '',
 email varchar(100) NOT NULL DEFAULT '',
 address varchar(255) NOT NULL DEFAULT '',
 sheba varchar(26) NOT NULL DEFAULT '',
 bank_name varchar(64) NOT NULL DEFAULT '',
 trade_type varchar(64) NOT NULL DEFAULT '',
 active tinyint(1) NOT NULL DEFAULT 1,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_by bigint(20) unsigned NOT NULL DEFAULT 0,
 created_at datetime NOT NULL,
 updated_by bigint(20) unsigned NOT NULL DEFAULT 0,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY kind (kind)",
            'ledger_accounts' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 code varchar(16) NOT NULL,
 title varchar(190) NOT NULL,
 level varchar(12) NOT NULL,
 nature varchar(8) NOT NULL,
 parent_code varchar(16) NOT NULL DEFAULT '',
 active tinyint(1) NOT NULL DEFAULT 1,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_by bigint(20) unsigned NOT NULL DEFAULT 0,
 created_at datetime NOT NULL,
 updated_by bigint(20) unsigned NOT NULL DEFAULT 0,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY code (code),
 KEY parent_code (parent_code)",
            'ledger_entries' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 doc_number varchar(20) NULL DEFAULT NULL,
 draft_number varchar(20) NOT NULL DEFAULT '',
 fiscal_year smallint(5) unsigned NOT NULL,
 entry_date date NOT NULL,
 description varchar(1000) NOT NULL,
 entry_type varchar(24) NOT NULL DEFAULT 'general',
 source_type varchar(24) NOT NULL DEFAULT 'manual',
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 status varchar(12) NOT NULL DEFAULT 'pending',
 reversal_of bigint(20) unsigned NULL DEFAULT NULL,
 reversal_target bigint(20) unsigned NULL DEFAULT NULL,
 total bigint(20) unsigned NOT NULL DEFAULT 0,
 created_by bigint(20) unsigned NOT NULL,
 created_at datetime NOT NULL,
 approved_by bigint(20) unsigned NULL DEFAULT NULL,
 approved_at datetime NULL DEFAULT NULL,
 rejected_by bigint(20) unsigned NULL DEFAULT NULL,
 rejected_at datetime NULL DEFAULT NULL,
 status_note varchar(1000) NOT NULL DEFAULT '',
 version int(10) unsigned NOT NULL DEFAULT 1,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY doc_number (doc_number),
 UNIQUE KEY reversal_of (reversal_of),
 KEY reversal_target (reversal_target),
 KEY status_date (status,entry_date),
 KEY fiscal_year (fiscal_year),
 KEY project_id (project_id)",
            'ledger_lines' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 entry_id bigint(20) unsigned NOT NULL,
 line_no smallint(5) unsigned NOT NULL,
 account_id bigint(20) unsigned NOT NULL,
 account_code varchar(16) NOT NULL,
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 cost_center_id bigint(20) unsigned NULL DEFAULT NULL,
 counterparty_id bigint(20) unsigned NULL DEFAULT NULL,
 cash_ref varchar(24) NULL DEFAULT NULL,
 description varchar(500) NOT NULL DEFAULT '',
 debit bigint(20) unsigned NOT NULL DEFAULT 0,
 credit bigint(20) unsigned NOT NULL DEFAULT 0,
 PRIMARY KEY  (id),
 KEY entry_id (entry_id),
 KEY account_code (account_code),
 KEY project_id (project_id),
 KEY cash_ref (cash_ref)",
            'ledger_events' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 source varchar(24) NOT NULL,
 source_id bigint(20) unsigned NOT NULL,
 event_type varchar(40) NOT NULL,
 entry_id bigint(20) unsigned NOT NULL,
 created_by bigint(20) unsigned NOT NULL DEFAULT 0,
 created_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY event (source,source_id,event_type),
 KEY entry_id (entry_id)",
            'treasury_accounts' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 kind varchar(8) NOT NULL DEFAULT 'bank',
 code varchar(32) NOT NULL,
 title varchar(190) NOT NULL,
 bank_name varchar(100) NOT NULL DEFAULT '',
 branch varchar(100) NOT NULL DEFAULT '',
 account_number varchar(40) NOT NULL DEFAULT '',
 sheba varchar(26) NOT NULL DEFAULT '',
 holder_name varchar(190) NOT NULL DEFAULT '',
 keeper_user_id bigint(20) unsigned NOT NULL DEFAULT 0,
 location varchar(190) NOT NULL DEFAULT '',
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 account_code varchar(16) NOT NULL,
 active tinyint(1) NOT NULL DEFAULT 1,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_by bigint(20) unsigned NOT NULL DEFAULT 0,
 created_at datetime NOT NULL,
 updated_by bigint(20) unsigned NOT NULL DEFAULT 0,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY code (code),
 KEY kind (kind)",
            'petty_funds' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 code varchar(32) NOT NULL,
 title varchar(190) NOT NULL,
 fund_type varchar(24) NOT NULL DEFAULT 'site_supervisor',
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 cost_center_id bigint(20) unsigned NULL DEFAULT NULL,
 holder_user_id bigint(20) unsigned NOT NULL DEFAULT 0,
 holder_name varchar(190) NOT NULL DEFAULT '',
 holder_phone varchar(32) NOT NULL DEFAULT '',
 account_code varchar(16) NOT NULL,
 ceiling bigint(20) unsigned NOT NULL DEFAULT 0,
 max_single_expense bigint(20) unsigned NOT NULL DEFAULT 0,
 min_balance_warning bigint(20) unsigned NOT NULL DEFAULT 0,
 source_account_id bigint(20) unsigned NULL DEFAULT NULL,
 active tinyint(1) NOT NULL DEFAULT 1,
 notes varchar(1000) NOT NULL DEFAULT '',
 period_start date NULL DEFAULT NULL,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_by bigint(20) unsigned NOT NULL DEFAULT 0,
 created_at datetime NOT NULL,
 updated_by bigint(20) unsigned NOT NULL DEFAULT 0,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY code (code),
 KEY project_id (project_id)",
            'petty_categories' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 name varchar(190) NOT NULL,
 subcategories text NULL,
 account_code varchar(16) NOT NULL,
 active tinyint(1) NOT NULL DEFAULT 1,
 sort_order int(10) unsigned NOT NULL DEFAULT 0,
 version int(10) unsigned NOT NULL DEFAULT 1,
 updated_by bigint(20) unsigned NOT NULL DEFAULT 0,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id)",
            'petty_expenses' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 number varchar(32) NOT NULL DEFAULT '',
 fund_id bigint(20) unsigned NOT NULL,
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 cost_center_id bigint(20) unsigned NULL DEFAULT NULL,
 category_id bigint(20) unsigned NULL DEFAULT NULL,
 category_name varchar(190) NOT NULL DEFAULT '',
 sub_category varchar(190) NOT NULL DEFAULT '',
 account_code varchar(16) NOT NULL DEFAULT '',
 expense_date date NOT NULL,
 amount bigint(20) unsigned NOT NULL,
 vendor varchar(190) NOT NULL DEFAULT '',
 vendor_national_id varchar(16) NOT NULL DEFAULT '',
 counterparty_id bigint(20) unsigned NULL DEFAULT NULL,
 invoice_number varchar(64) NOT NULL DEFAULT '',
 invoice_date date NULL DEFAULT NULL,
 description varchar(1000) NOT NULL DEFAULT '',
 payment_method varchar(24) NOT NULL DEFAULT 'cash',
 status varchar(16) NOT NULL DEFAULT 'pending',
 approval_level varchar(32) NOT NULL DEFAULT '',
 chain varchar(255) NOT NULL DEFAULT '',
 step_index tinyint(3) unsigned NOT NULL DEFAULT 0,
 history longtext NULL,
 submitted_by bigint(20) unsigned NOT NULL,
 last_approved_by bigint(20) unsigned NULL DEFAULT NULL,
 reject_reason varchar(1000) NOT NULL DEFAULT '',
 entry_id bigint(20) unsigned NULL DEFAULT NULL,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_at datetime NOT NULL,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY fund_status (fund_id,status),
 KEY project_id (project_id),
 KEY status (status)",
            'petty_requests' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 number varchar(32) NOT NULL DEFAULT '',
 fund_id bigint(20) unsigned NOT NULL,
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 amount bigint(20) unsigned NOT NULL,
 reason varchar(1000) NOT NULL DEFAULT '',
 request_date date NOT NULL,
 status varchar(16) NOT NULL DEFAULT 'pending',
 chain varchar(255) NOT NULL DEFAULT '',
 step_index tinyint(3) unsigned NOT NULL DEFAULT 0,
 history longtext NULL,
 requested_by bigint(20) unsigned NOT NULL,
 last_approved_by bigint(20) unsigned NULL DEFAULT NULL,
 reject_reason varchar(1000) NOT NULL DEFAULT '',
 payment_request_id bigint(20) unsigned NULL DEFAULT NULL,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_at datetime NOT NULL,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY fund_status (fund_id,status),
 KEY status (status)",
            'petty_counts' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 number varchar(32) NOT NULL DEFAULT '',
 fund_id bigint(20) unsigned NOT NULL,
 period_start date NULL DEFAULT NULL,
 period_end date NOT NULL,
 book_balance bigint(20) NOT NULL DEFAULT 0,
 pending_expenses bigint(20) unsigned NOT NULL DEFAULT 0,
 expected_balance bigint(20) NOT NULL DEFAULT 0,
 counted_cash bigint(20) unsigned NOT NULL DEFAULT 0,
 discrepancy bigint(20) NOT NULL DEFAULT 0,
 reason varchar(1000) NOT NULL DEFAULT '',
 notes varchar(1000) NOT NULL DEFAULT '',
 entry_id bigint(20) unsigned NULL DEFAULT NULL,
 closes_period tinyint(1) NOT NULL DEFAULT 0,
 counted_by bigint(20) unsigned NOT NULL,
 created_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY fund_id (fund_id)",
            'payment_requests' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 number varchar(32) NOT NULL DEFAULT '',
 source_type varchar(24) NOT NULL DEFAULT 'manual',
 source_id bigint(20) unsigned NOT NULL DEFAULT 0,
 payable_type varchar(32) NOT NULL DEFAULT '',
 debit_account_code varchar(16) NOT NULL,
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 cost_center_id bigint(20) unsigned NULL DEFAULT NULL,
 counterparty_id bigint(20) unsigned NULL DEFAULT NULL,
 fund_id bigint(20) unsigned NULL DEFAULT NULL,
 beneficiary_name varchar(190) NOT NULL DEFAULT '',
 beneficiary_type varchar(64) NOT NULL DEFAULT '',
 beneficiary_sheba varchar(26) NOT NULL DEFAULT '',
 amount bigint(20) unsigned NOT NULL,
 paid_amount bigint(20) unsigned NOT NULL DEFAULT 0,
 request_date date NOT NULL,
 due_date date NOT NULL,
 priority varchar(12) NOT NULL DEFAULT 'normal',
 status varchar(16) NOT NULL DEFAULT 'pending',
 description varchar(1000) NOT NULL DEFAULT '',
 requested_by bigint(20) unsigned NOT NULL,
 approved_by bigint(20) unsigned NULL DEFAULT NULL,
 approved_at datetime NULL DEFAULT NULL,
 reject_reason varchar(1000) NOT NULL DEFAULT '',
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_at datetime NOT NULL,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY source (source_type,source_id),
 KEY status_due (status,due_date),
 KEY project_id (project_id)",
            'payments' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 payment_request_id bigint(20) unsigned NOT NULL,
 account_id bigint(20) unsigned NOT NULL,
 amount bigint(20) unsigned NOT NULL,
 method varchar(16) NOT NULL DEFAULT 'transfer',
 tracking varchar(64) NOT NULL DEFAULT '',
 pay_date date NOT NULL,
 cheque_id bigint(20) unsigned NULL DEFAULT NULL,
 entry_id bigint(20) unsigned NULL DEFAULT NULL,
 paid_by bigint(20) unsigned NOT NULL,
 created_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY payment_request_id (payment_request_id)",
            'receipts' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 number varchar(32) NOT NULL DEFAULT '',
 receipt_type varchar(16) NOT NULL DEFAULT 'statement',
 credit_account_code varchar(16) NOT NULL,
 counterparty_id bigint(20) unsigned NULL DEFAULT NULL,
 payer_name varchar(190) NOT NULL DEFAULT '',
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 account_id bigint(20) unsigned NOT NULL,
 amount bigint(20) unsigned NOT NULL,
 receipt_date date NOT NULL,
 method varchar(16) NOT NULL DEFAULT 'transfer',
 tracking varchar(64) NOT NULL DEFAULT '',
 cheque_number varchar(40) NOT NULL DEFAULT '',
 cheque_bank varchar(100) NOT NULL DEFAULT '',
 cheque_due_date date NULL DEFAULT NULL,
 cheque_id bigint(20) unsigned NULL DEFAULT NULL,
 statement_id bigint(20) unsigned NULL DEFAULT NULL,
 contract_id bigint(20) unsigned NULL DEFAULT NULL,
 description varchar(1000) NOT NULL DEFAULT '',
 status varchar(16) NOT NULL DEFAULT 'pending',
 created_by bigint(20) unsigned NOT NULL,
 approved_by bigint(20) unsigned NULL DEFAULT NULL,
 approved_at datetime NULL DEFAULT NULL,
 reject_reason varchar(1000) NOT NULL DEFAULT '',
 entry_id bigint(20) unsigned NULL DEFAULT NULL,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_at datetime NOT NULL,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY status (status),
 KEY project_id (project_id)",
            'transfers' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 number varchar(32) NOT NULL DEFAULT '',
 from_account_id bigint(20) unsigned NOT NULL,
 to_account_id bigint(20) unsigned NOT NULL,
 amount bigint(20) unsigned NOT NULL,
 transfer_date date NOT NULL,
 tracking varchar(64) NOT NULL DEFAULT '',
 description varchar(1000) NOT NULL DEFAULT '',
 entry_id bigint(20) unsigned NULL DEFAULT NULL,
 created_by bigint(20) unsigned NOT NULL,
 created_at datetime NOT NULL,
 PRIMARY KEY  (id)",
            'cheques' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 direction varchar(12) NOT NULL,
 serial varchar(40) NOT NULL,
 bank_name varchar(100) NOT NULL DEFAULT '',
 amount bigint(20) unsigned NOT NULL,
 issue_date date NOT NULL,
 due_date date NOT NULL,
 counterparty_id bigint(20) unsigned NULL DEFAULT NULL,
 party_name varchar(190) NOT NULL DEFAULT '',
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 account_id bigint(20) unsigned NULL DEFAULT NULL,
 source_type varchar(16) NOT NULL DEFAULT '',
 source_id bigint(20) unsigned NOT NULL DEFAULT 0,
 counter_account_code varchar(16) NOT NULL DEFAULT '',
 counter_cash_ref varchar(24) NULL DEFAULT NULL,
 status varchar(12) NOT NULL DEFAULT 'pending',
 status_date date NULL DEFAULT NULL,
 status_note varchar(1000) NOT NULL DEFAULT '',
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_by bigint(20) unsigned NOT NULL,
 created_at datetime NOT NULL,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY direction_status (direction,status),
 KEY due_date (due_date)",
            'bank_statement_lines' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 account_id bigint(20) unsigned NOT NULL,
 line_date date NOT NULL,
 description varchar(500) NOT NULL DEFAULT '',
 reference varchar(64) NOT NULL DEFAULT '',
 direction varchar(12) NOT NULL,
 amount bigint(20) unsigned NOT NULL,
 status varchar(12) NOT NULL DEFAULT 'unmatched',
 matched_line_id bigint(20) unsigned NULL DEFAULT NULL,
 voucher_entry_id bigint(20) unsigned NULL DEFAULT NULL,
 matched_by bigint(20) unsigned NULL DEFAULT NULL,
 batch varchar(40) NOT NULL DEFAULT '',
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_by bigint(20) unsigned NOT NULL,
 created_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY matched_line_id (matched_line_id),
 KEY account_status (account_id,status)",
            'audit_log' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 user_id bigint(20) unsigned NOT NULL,
 action varchar(64) NOT NULL,
 object_type varchar(32) NOT NULL,
 object_id bigint(20) unsigned NOT NULL DEFAULT 0,
 object_ref varchar(64) NOT NULL DEFAULT '',
 before_data longtext NULL,
 after_data longtext NULL,
 request_key varchar(100) NOT NULL DEFAULT '',
 created_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY object (object_type,object_id),
 KEY user_id (user_id),
 KEY created_at (created_at)",
            'idempotency_keys' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 user_id bigint(20) unsigned NOT NULL,
 idem_key varchar(100) NOT NULL,
 route varchar(191) NOT NULL,
 request_hash char(64) NOT NULL,
 status_code smallint(5) unsigned NOT NULL DEFAULT 0,
 response longtext NULL,
 created_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY user_key (user_id,idem_key),
 KEY created_at (created_at)",
            'ai_requests' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 user_id bigint(20) unsigned NOT NULL,
 day date NOT NULL,
 created_at datetime NOT NULL,
 status varchar(16) NOT NULL DEFAULT 'pending',
 provider varchar(16) NOT NULL DEFAULT '',
 model varchar(100) NOT NULL DEFAULT '',
 input_tokens int(10) unsigned NOT NULL DEFAULT 0,
 output_tokens int(10) unsigned NOT NULL DEFAULT 0,
 question_chars smallint(5) unsigned NOT NULL DEFAULT 0,
 error_code varchar(32) NOT NULL DEFAULT '',
 question longtext NULL,
 answer longtext NULL,
 PRIMARY KEY  (id),
 KEY user_day (user_id,day),
 KEY created_at (created_at)",
            'documents' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 doc_number varchar(40) NOT NULL,
 title varchar(190) NOT NULL,
 doc_type varchar(40) NOT NULL DEFAULT 'other',
 description varchar(1000) NOT NULL DEFAULT '',
 project_id bigint(20) unsigned NULL DEFAULT NULL,
 cost_center_id bigint(20) unsigned NULL DEFAULT NULL,
 counterparty_id bigint(20) unsigned NULL DEFAULT NULL,
 file_name varchar(255) NOT NULL,
 stored_name varchar(100) NOT NULL,
 mime varchar(100) NOT NULL,
 size bigint(20) unsigned NOT NULL DEFAULT 0,
 sha256 char(64) NOT NULL,
 version int(10) unsigned NOT NULL DEFAULT 1,
 uploaded_by bigint(20) unsigned NOT NULL,
 uploaded_at datetime NOT NULL,
 status varchar(12) NOT NULL DEFAULT 'active',
 archived_by bigint(20) unsigned NULL DEFAULT NULL,
 archived_at datetime NULL DEFAULT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY doc_number (doc_number),
 KEY project_id (project_id),
 KEY sha256 (sha256),
 KEY status (status)",
            'document_links' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 document_id bigint(20) unsigned NOT NULL,
 entity_type varchar(24) NOT NULL,
 entity_id varchar(64) NOT NULL,
 created_by bigint(20) unsigned NOT NULL DEFAULT 0,
 created_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY link (document_id,entity_type,entity_id),
 KEY entity (entity_type,entity_id)",
            // 0.7.0: client contracts (kind client) and subcontracts (kind subcontract). Rates are basis points
            // (1% = 100); quantities DECIMAL(18,3); amounts integer Rials computed by the server.
            'contracts' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 number varchar(32) NOT NULL DEFAULT '',
 kind varchar(16) NOT NULL,
 contract_no varchar(64) NOT NULL DEFAULT '',
 title varchar(190) NOT NULL DEFAULT '',
 project_id bigint(20) unsigned NOT NULL,
 cost_center_id bigint(20) unsigned NULL DEFAULT NULL,
 counterparty_id bigint(20) unsigned NOT NULL,
 trade_type varchar(100) NOT NULL DEFAULT '',
 amount bigint(20) unsigned NOT NULL DEFAULT 0,
 contract_date date NULL DEFAULT NULL,
 start_date date NULL DEFAULT NULL,
 end_date date NULL DEFAULT NULL,
 duration_days int(10) unsigned NOT NULL DEFAULT 0,
 advance_bp int(10) unsigned NOT NULL DEFAULT 0,
 retention_bp int(10) unsigned NOT NULL DEFAULT 0,
 insurance_bp int(10) unsigned NOT NULL DEFAULT 0,
 tax_bp int(10) unsigned NOT NULL DEFAULT 0,
 other_bp int(10) unsigned NOT NULL DEFAULT 0,
 adjustment_base_index decimal(12,2) NULL DEFAULT NULL,
 adjustment_factor_bp int(10) unsigned NOT NULL DEFAULT 0,
 description varchar(1000) NOT NULL DEFAULT '',
 status varchar(16) NOT NULL DEFAULT 'pending',
 chain varchar(255) NOT NULL DEFAULT '',
 step_index tinyint(3) unsigned NOT NULL DEFAULT 0,
 history longtext NULL,
 last_approved_by bigint(20) unsigned NULL DEFAULT NULL,
 reject_reason varchar(1000) NOT NULL DEFAULT '',
 created_by bigint(20) unsigned NOT NULL,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_at datetime NOT NULL,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY project_id (project_id),
 KEY counterparty_id (counterparty_id),
 KEY kind_status (kind,status)",
            'contract_lines' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 contract_id bigint(20) unsigned NOT NULL,
 amendment_id bigint(20) unsigned NULL DEFAULT NULL,
 row_no int(10) unsigned NOT NULL DEFAULT 0,
 code varchar(32) NOT NULL DEFAULT '',
 description varchar(300) NOT NULL DEFAULT '',
 unit varchar(32) NOT NULL DEFAULT '',
 quantity decimal(18,3) NOT NULL DEFAULT 0,
 rate bigint(20) unsigned NOT NULL DEFAULT 0,
 amount bigint(20) unsigned NOT NULL DEFAULT 0,
 created_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY contract_id (contract_id)",
            'contract_amendments' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 number varchar(32) NOT NULL DEFAULT '',
 contract_id bigint(20) unsigned NOT NULL,
 amendment_no varchar(64) NOT NULL DEFAULT '',
 amendment_date date NULL DEFAULT NULL,
 amount_delta bigint(20) NOT NULL DEFAULT 0,
 extend_days int(10) unsigned NOT NULL DEFAULT 0,
 description varchar(1000) NOT NULL DEFAULT '',
 status varchar(16) NOT NULL DEFAULT 'pending',
 created_by bigint(20) unsigned NOT NULL,
 approved_by bigint(20) unsigned NULL DEFAULT NULL,
 approved_at datetime NULL DEFAULT NULL,
 reject_reason varchar(1000) NOT NULL DEFAULT '',
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_at datetime NOT NULL,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY contract_id (contract_id)",
            'amendment_lines' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 amendment_id bigint(20) unsigned NOT NULL,
 contract_line_id bigint(20) unsigned NULL DEFAULT NULL,
 creates_line tinyint(1) unsigned NOT NULL DEFAULT 0,
 code varchar(32) NOT NULL DEFAULT '',
 description varchar(300) NOT NULL DEFAULT '',
 unit varchar(32) NOT NULL DEFAULT '',
 rate bigint(20) unsigned NOT NULL DEFAULT 0,
 quantity_delta decimal(18,3) NOT NULL DEFAULT 0,
 amount bigint(20) NOT NULL DEFAULT 0,
 PRIMARY KEY  (id),
 KEY amendment_id (amendment_id),
 KEY contract_line_id (contract_line_id)",
            'contract_guarantees' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 contract_id bigint(20) unsigned NOT NULL,
 kind varchar(24) NOT NULL DEFAULT 'performance',
 guarantee_no varchar(64) NOT NULL DEFAULT '',
 bank varchar(100) NOT NULL DEFAULT '',
 amount bigint(20) unsigned NOT NULL DEFAULT 0,
 issue_date date NULL DEFAULT NULL,
 due_date date NULL DEFAULT NULL,
 status varchar(16) NOT NULL DEFAULT 'active',
 notes varchar(1000) NOT NULL DEFAULT '',
 created_by bigint(20) unsigned NOT NULL,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_at datetime NOT NULL,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY contract_id (contract_id),
 KEY due (status,due_date)",
            // Client statements (kind client) and subcontractor statements (kind subcontract).
            'statements' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 number varchar(32) NOT NULL DEFAULT '',
 kind varchar(16) NOT NULL,
 title varchar(190) NOT NULL DEFAULT '',
 contract_id bigint(20) unsigned NOT NULL,
 project_id bigint(20) unsigned NOT NULL,
 cost_center_id bigint(20) unsigned NULL DEFAULT NULL,
 counterparty_id bigint(20) unsigned NOT NULL,
 period_start date NULL DEFAULT NULL,
 period_end date NULL DEFAULT NULL,
 status varchar(32) NOT NULL DEFAULT 'draft',
 include_vat tinyint(1) unsigned NOT NULL DEFAULT 1,
 work_amount bigint(20) unsigned NOT NULL DEFAULT 0,
 adjustment_index decimal(12,2) NULL DEFAULT NULL,
 adjustment_amount bigint(20) unsigned NOT NULL DEFAULT 0,
 vat_rate int(10) unsigned NOT NULL DEFAULT 0,
 vat_amount bigint(20) unsigned NOT NULL DEFAULT 0,
 gross_amount bigint(20) unsigned NOT NULL DEFAULT 0,
 fixed_deduction bigint(20) unsigned NOT NULL DEFAULT 0,
 deductions longtext NULL,
 total_deductions bigint(20) unsigned NOT NULL DEFAULT 0,
 net_amount bigint(20) unsigned NOT NULL DEFAULT 0,
 employer_ref varchar(64) NOT NULL DEFAULT '',
 employer_date date NULL DEFAULT NULL,
 description varchar(1000) NOT NULL DEFAULT '',
 history longtext NULL,
 last_approved_by bigint(20) unsigned NULL DEFAULT NULL,
 reject_reason varchar(1000) NOT NULL DEFAULT '',
 entry_id bigint(20) unsigned NULL DEFAULT NULL,
 void_entry_id bigint(20) unsigned NULL DEFAULT NULL,
 payment_request_id bigint(20) unsigned NULL DEFAULT NULL,
 approved_at datetime NULL DEFAULT NULL,
 created_by bigint(20) unsigned NOT NULL,
 version int(10) unsigned NOT NULL DEFAULT 1,
 created_at datetime NOT NULL,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id),
 KEY contract_id (contract_id),
 KEY project_id (project_id),
 KEY kind_status (kind,status)",
            'statement_lines' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 statement_id bigint(20) unsigned NOT NULL,
 contract_line_id bigint(20) unsigned NOT NULL,
 previous_quantity decimal(18,3) NOT NULL DEFAULT 0,
 quantity decimal(18,3) NOT NULL DEFAULT 0,
 rate bigint(20) unsigned NOT NULL DEFAULT 0,
 amount bigint(20) unsigned NOT NULL DEFAULT 0,
 PRIMARY KEY  (id),
 KEY statement_id (statement_id),
 KEY contract_line_id (contract_line_id)",
            // 0.6.1: one row (id 1) with the letterhead and the signatories of printed reports (JSON), versioned.
            'report_settings' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 settings longtext NULL,
 logo_id bigint(20) unsigned NULL DEFAULT NULL,
 version int(10) unsigned NOT NULL DEFAULT 1,
 updated_by bigint(20) unsigned NOT NULL DEFAULT 0,
 updated_at datetime NOT NULL,
 PRIMARY KEY  (id)",
            'doc_sequences' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 prefix varchar(8) NOT NULL,
 fiscal_year smallint(5) unsigned NOT NULL,
 seq int(10) unsigned NOT NULL,
 object_type varchar(32) NOT NULL DEFAULT '',
 object_id bigint(20) unsigned NOT NULL DEFAULT 0,
 issued_by bigint(20) unsigned NOT NULL DEFAULT 0,
 issued_at datetime NOT NULL,
 PRIMARY KEY  (id),
 UNIQUE KEY number (prefix,fiscal_year,seq)",
        );
    }

    public static function maybe_migrate() {
        if (get_option(self::OPTION_VERSION) === self::DB_VERSION) {
            return;
        }
        if (get_transient(self::TRANSIENT_BACKOFF)) {
            return; // the last attempt left tables off InnoDB: retried after the backoff or from the settings screen
        }
        self::migrate();
    }

    /**
     * Additive migration. Returns the engine problems found (empty when every table is InnoDB).
     * The version is stored only when all tables exist on InnoDB; otherwise every command answers 503 and
     * the automatic retry waits for the backoff transient to expire.
     *
     * Versions: 1 — tables of 0.3.0; 2 — ledger_entries.reversal_target (the entry a reversal reverses, kept
     * after a rejected reversal releases reversal_of); 3 — ai_requests (assistant requests: audit and daily limit); 4 — documents and document_links (document
     * center and attachments; files in wp-content/uploads/akph-private); 5 — ledger_lines.cash_ref, ledger_events (one entry
     * per business event) and the tables of petty cash, treasury and bank reconciliation; 6 — report_settings (company
     * letterhead, logo and signatories of printed reports, one versioned row); 7 — contracts, contract_lines (BOQ),
     * contract_amendments, amendment_lines, contract_guarantees, statements, statement_lines (client and
     * subcontractor progress statements) and receipts.statement_id / contract_id (0.7.0).
     */
    public static function migrate() {
        global $wpdb;
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        $collate = $wpdb->get_charset_collate();
        $problems = array();
        foreach (self::definitions() as $name => $columns) {
            $table = self::table($name);
            dbDelta("CREATE TABLE {$table} (\n {$columns}\n) ENGINE=InnoDB {$collate};");
            $engine = self::engine($table);
            if ($engine !== 'innodb') {
                $problems[] = $table . ':' . ($engine === '' ? 'missing' : $engine);
            }
        }
        update_option(self::OPTION_ENGINE_PROBLEMS, $problems, false);
        if ($problems) {
            set_transient(self::TRANSIENT_BACKOFF, 1, self::BACKOFF_SECONDS);
            return $problems;
        }
        self::backfill();
        delete_transient(self::TRANSIENT_BACKOFF);
        update_option(self::OPTION_VERSION, self::DB_VERSION, false);
        return $problems;
    }

    /** Data steps of the versions above; each is idempotent (runs again harmlessly). */
    private static function backfill() {
        global $wpdb;
        $entries = self::table('ledger_entries');
        // v2: reversals issued by 0.3.0 get their target.
        $wpdb->query("UPDATE {$entries} SET reversal_target = reversal_of WHERE reversal_of IS NOT NULL AND reversal_target IS NULL");
    }

    private static function engine($table) {
        global $wpdb;
        $status = $wpdb->get_row($wpdb->prepare('SHOW TABLE STATUS WHERE Name = %s', $table));
        return $status && isset($status->Engine) ? strtolower((string) $status->Engine) : '';
    }

    /** Commands run only on a 64-bit PHP with every table migrated on InnoDB. */
    public static function ready() {
        return PHP_INT_SIZE >= 8 && get_option(self::OPTION_VERSION) === self::DB_VERSION && !get_option(self::OPTION_ENGINE_PROBLEMS);
    }
}
